version: '3.9'

services:

  mongodb:
    image: mongo:7
    container_name: mongodb

    restart: always

    ports:
      - "27018:27018"

    volumes:
      - mongo_data:/data/db

  api:
    #build: ./api
    
    image: iheb49/todo-api:v1
    
    container_name: todo-api

    restart: always

    

    environment:
      MONGO_URI: mongodb://mongodb:27017/todos

    depends_on:
      - mongodb
   
  nginx:
    image: nginx:latest

    restart: always

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - api    

volumes:
  mongo_data:
